### ISSUE TITLE
Cannot find module emmet/emmet

### ISSUE THREAD

**Issue by viraj-khatavkar** [chairuosen/vue-ace-editor#1]
`app.js:1Uncaught Error: Cannot find module 'emmet/emmet'`

**Comment by chairuosen** [comment]
@viraj-khatavkar 
1.Which version of node/npm do you have?
2.Did you install vue-ace-editor successfully? 

Please check the dir `node_modules/emmet`( in npm v3 ) or `node_modules/vue-ace-editor/emmet`(in npm v2 or 1) and make sure emmet(https://github.com/cloud9ide/emmet-core) is installed successfully.

**Comment by viraj-khatavkar** [comment]
Hi @chairuosen 

node - 6.2.0
npm - 3.9.6

Refer below screenshot for more details.

![screen shot 2016-07-25 at 4 29 23 pm](https://cloud.githubusercontent.com/assets/5693836/17099294/1c230d6c-5285-11e6-82fd-5b793a02f7d0.png)
![screen shot 2016-07-25 at 4 29 37 pm](https://cloud.githubusercontent.com/assets/5693836/17099295/1c36488c-5285-11e6-8c0f-bf339ce4d6de.png)

**Comment by chairuosen** [comment]
@viraj-khatavkar 
Well.....I've tried it with your node version, but it works fine..

Heres a demo for you https://github.com/chairuosen/vue-ace-editor-demo
Can you try the demo and see if it works or not.

**Comment by viraj-khatavkar** [comment]
@chairuosen it works in the above demo, but if I follow the same steps in my integration with Laravel to use it inside a component, it gives me error. Please find below image & code for reference :

![screen shot 2016-07-26 at 12 18 14 pm](https://cloud.githubusercontent.com/assets/5693836/17128570/451665d8-532b-11e6-81ad-345814491d15.png)

## config-files.js (component)

``````
import {Multiselect} from "vue-multiselect";

Vue.component('config-files', {
    props: ['user', 'project'],

    components: {
        Multiselect,
        editor:require('vue-ace-editor')
    },
    events:{
        'vue-ace-editor:init':function () {
            require('brace/mode/html');
            require('brace/theme/chrome');
        }
    },
    data() {
        return {
            addForm: new SparkForm({
                deployment_path: '',
                name: '',
                server_ids: [],
                code: ''
            }),
            editForm: new SparkForm({
                deployment_path: '',
                name: '',
                server_ids: [],
                code: '',
                config_file_id: null
            }),
            content: '',
            options: this.project.servers,
            selected: null,
            deleteForm: new SparkForm({}),
        }
    },

    ready() {
        // var editor = ace.edit("config-files-ace");
        // editor.setShowPrintMargin(false);
    },

    computed: {},

    methods: {
        create() {

            Spark.post('/api/projects/' + this.project.id + '/config-files/store', this.addForm)
                .then(response => {
                    this.project = response.data;

                    this.addForm.deployment_path = '';
                    this.addForm.name = '';
                    this.addForm.server_ids = [];
                    this.addForm.code = '';
                    this.selected = this.project.servers;
                    this.options = this.project.servers;

                    $('#addConfigFileModal').modal('hide');

                });
        },
        deleteFile(configFile) {

            Spark.post('/api/projects/' + this.project.id + '/config-files/' + configFile.id + '/delete', this.deleteForm)
                .then(response => {
                    this.project = response.data;
                });

        },
        update(configFile) {

            Spark.post('/api/projects/' + this.project.id + '/config-files/' + this.editForm.config_file_id + '/update', this.editForm)
                .then(response => {
                    this.project = response.data;

                    this.editForm.deployment_path = '';
                    this.editForm.name = '';
                    this.editForm.server_ids = [];
                    this.editForm.code = '';
                    this.selected = this.project.servers;
                    this.options = this.project.servers;

                    $('#editConfigFileModal').modal('hide');

                });
        },
        editConfigFile(configFile) {
            this.editForm.deployment_path = configFile.deployment_path;
            this.editForm.name = configFile.name;
            this.editForm.code = configFile.code;
            this.editForm.config_file_id = configFile.id;
            this.selected = configFile.servers;
        }
    },
    watch: {
        selected: function (selected) {
            if (selected != null) {
                var selected_servers = [];

                $.each(selected, function (index, value) {
                    selected_servers[index] = value.id;
                });

                this.addForm.server_ids = selected_servers;
                this.editForm.server_ids = selected_servers;
            }
        }
    }
});```
``````

**Comment by chairuosen** [comment]
@viraj-khatavkar

 What build system do you use ? Seems not Webpack.

On the other way, you can try `brace` yourself, without vue-ace-editor. vue-ace-editor is just a simple packaging of brace.

**Comment by viraj-khatavkar** [comment]
@chairuosen I use browserify, so this is not for me :(

**Comment by chairuosen** [comment]
@viraj-khatavkar wait... browserify is also a commonJS loader. I think i got the point, the async require. It should works fine with a little fix.

**Comment by viraj-khatavkar** [comment]
@chairuosen sure, let me know once you have the fix in place 👍

**Comment by chairuosen** [comment]
@viraj-khatavkar 
Test done. Although my code can be compatible with browserify. the `emmet` goes error.....
I don't want to delete emmet from my repo cause it's a good feature. So you may not be able to use my repo with browserify..
But you can fork it and do the following step to use it by your own repo.
1. fork my repo.
2. delete these code from line 3 in `index.js`
   
   ```
   require(['emmet/emmet'],function (data) {
       window.emmet = data.emmet;
   });
   ```
3. change the resource url in your project's package.json
   
   ```
   "vue-ace-editor": "git+FORKED_REPO_URL",
   ```

**Comment by monkindey** [comment]
I think the emmet library has the **Octal literal in strict mode**, Because it show the error in my terminal
