### ISSUE TITLE
vue-ace-editor doesn't work for Vue2.0

### ISSUE THREAD

**Issue by monkindey** [chairuosen/vue-ace-editor#2]

**Comment by Kaijun** [comment]
+1

**Comment by chairuosen** [comment]
@Kaijun @monkindey Vue2跟Vue1的写法有很多不同啊，没法同时兼容，一般是另起一个repo做还是在分支里做比较好？

**Comment by monkindey** [comment]
语法确实变了很多呀，自定义事件局限了很多。

暂时修改了下你的代码，暂时可以使用，不知道后面有啥坑没
1. ready 变成 **mounted**
2. 不要

``` javascript
vm.$dispatch('vue-ace-editor:init');
```

直接在mounted生命周期钩子写上

``` javascript
require('brace/mode/javascript');
require('brace/theme/monokai');
```

还有不要掉emmet库了, 里面存在八进制，严格模式下编译出现问题了

``` javascript
// require(['emmet/emmet'],function (data) {
//     window.emmet = data.emmet;
// });
```

有一个问题就是为啥要用到事件机制呢？比如下面的代码

``` javascript
vm.$dispatch('vue-ace-editor:init');
```

**Comment by chairuosen** [comment]
@monkindey 在mounted里面写死就不能由调用者自定义了呀

**Comment by chairuosen** [comment]
https://github.com/chairuosen/vue2-ace-editor

**Comment by monkindey** [comment]
赞，学习了。

有一个题外话，有关 Vue的**异步更新队列**的问题，如果我想实现点击运行的时候，
列表一步一步高亮，可以设置间隔500毫秒，每隔500毫秒就高亮下一个。

例子 https://jsfiddle.net/monkindey/zkf6v69u/

但是因为Vue本身的异步更新队列，导致修改某个state在同一个事件循环只会更改一次。
所以导致点击运行之后第一个高亮了，然后就最后一个高亮了。

只能用一些setTimeout 和 nextTick方式去hack了，但是个人不太喜欢这种方式。
看了下vue2还有 forceUpdate，但是可能是我用的姿势不对还是咋地，也不行。

想请问你，你有更好的解决方案么？

**Comment by chairuosen** [comment]
@monkindey 隔500毫秒才发生的事情肯定要异步的写法才能实现，这没辙。

**Comment by monkindey** [comment]
@chairuosen  不是，我可以用js模拟sleep，让程序500毫秒不做啥事情哦

简单代码

``` javascript
function delay(duration) {
    var d = new Date().getTime();
    while(+new Date() < d + duration) { /* no-op */ }
}
```

我调用**delay(500)**就行，是不是呢？
问题我这么做的话，会导致这个还是同一个事件循环里面，所以出现了不会
立即更新页面的问题，Vue会等一个事件循环后再去更新页面

不知道我有没表达清楚呢?

**Comment by chairuosen** [comment]
@monkindey 。。。。你这样是阻塞了js，while是同步的，cpu在这里转圈不执行其他代码，vue的代码也不会执行。

**Comment by monkindey** [comment]
这么跟你说吧，感觉我没有表达清楚哈

### 功能

点击运行时候，列表会每隔500毫秒高亮，顺序从上往下

### 实现

可以参考 https://jsfiddle.net/monkindey/zkf6v69u/ demo，简单说下我的思路，
1. 通过v-for 然后根据**runId**来标记到哪一行了，如果列表的**index**跟**runId**一致的话，就设置它的class，也就是高亮。
2. 问题就在于点击运行的时候，触发运行的逻辑，想法肯定是每隔500毫秒去修改 **runId**，是吧。

``` javascript
methods: {
run: function() {
    delay(500)
    this.runId = 1;
    delay(500)
    this.runId = 2;
 }
}
```

但是刚好就是在同一个事件循环里面，Vue不会立即去触发re-render，导致等了 1s(500ms+500ms) 才会渲染页面，这个时候runId已经等于2了，所以页面只会高亮第一个和最后一个。

这样子写可能很直观就能猜到是异步更新队列的问题，之前用的是**vuex**去写，以为
每次更新state，都会刷新一次，被redux影响了。

**Comment by chairuosen** [comment]
@monkindey 这写法好像php，反正js不能这样写的。。。。
你要是想类似同步实现的话只能用 Promise,co,async function这样的东西。关于vue什么时候rerender的问题我不太清楚，你可以去[论坛](http://forum.vuejs.org/)问问

**Comment by monkindey** [comment]
@chairuosen  先感谢啦

如果是你来实现这个功能的话，你会怎么做呢？

**Comment by Kaijun** [comment]
@monkindey 你用while会阻塞主进程的，然后整个页面卡死

这个功能本质就是 一直异步，如果用传统回调方式的话，可以写个递归来一直回调。

如果用async await的话就很简单了。。。封装一个 sleep 方法 返回 promise 里面是个setTimeout
然后 想等待500ms的时候 就直接 await sleep(500) 就行了
最后就是for循环你这个列表 然后 修改class高亮，await sleep(500), 就完了。代码看起来是同步的 实际上是异步的

**Comment by monkindey** [comment]
@Kaijun  非常感谢你的回复

对 **async await** 不是太清楚，麻烦能在 https://jsfiddle.net/monkindey/zkf6v69u/ 基础上实现来学习下么？虽然有点伸手党。

我这边也再仔细看看**async await**这种方式，之前用了setTimeout + nextTick 实现了，但是不喜欢这种方式。

**Comment by Kaijun** [comment]
@monkindey ...最好自己实现下
https://jsfiddle.net/zkf6v69u/2/ 这是用递归的办法。。。
async await的话 建议你先看下原理 而且jsfiddle上也不好操作

**Comment by monkindey** [comment]
@Kaijun 非常感谢你的解答，我再仔细看看**async await** 

@chairuosen  也谢谢这个issue，不好意思占用大家的timeline了。
